"""add episode_count to dramas

Revision ID: c608da26c891
Revises: 0b3fe79c34b8
Create Date: 2026-09-27 22:57:15.314235
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'c608da26c891'
down_revision: str | None = '0b3fe79c34b8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dramas', sa.Column('episode_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dramas', 'episode_count')
    # ### end Alembic commands ###
